debug: true
#server:
#  port: 8080
#  servlet:
#    context-path: /api
spring:
  profiles:
    default: test
    active: local

# 작성한 yml(설정 파일)들은 빌드 과정에서 JAR에 포함됩니다.
# 따라서 JAR 파일을 실행하는 단계에 전달하는 인자를 전달하는 방식으로 사용할 profile을 정할 수도 있습니다.
# 또는 환경변수로 전달할 수도 있습니다.



#    thymeleaf:
#      prefix: classpath:/templates/
#      suffix: .html
#      cache: false
