spring:
  config:
    activate:
      on-profile: test
  datasource:
    #    url: jdbc:h2:~/kaushop
    url: jdbc:h2:tcp://localhost/~/kaushop2
    #    url: jdbc:h2:mem:kaushop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true